In [ ]:
What is Numpy

- numerical python
- used for computation and processiong of single dimension or multidem array
- this lib is written in c
- it is very fast execution

In [1]:
!pip install numpy

In [2]:
import numpy as np

# How to create a array

In [4]:
# 1. using list or tuple

list_1 = [1,2,3,4,5]
print(type(list_1))

arr_1 = np.array(list_1)
type(arr_1)

<class 'list'>


numpy.ndarray

In [5]:
tuple_1 = (1,2,3,4,5)
print(type(list_1))

arr_1 = np.array(list_1)
type(arr_1)

<class 'list'>


numpy.ndarray

In [6]:
arr_1

array([1, 2, 3, 4, 5])

In [10]:
# how many elements are der in array

# ans -5 
# len(arr_1)
arr_1.size

5

In [8]:
# WHAY IS THE SHAPE OF AN ARRAY

# 5
arr_1.shape

(5,)

In [9]:
# if we want to know the dimesnion of an array

arr_1.ndim

1

In [11]:
# creating a multi demsional array

list_2 = [[1,2,3,4] , [5,6,7,8]]

arr_3 = np.array(list_2)

In [13]:
arr_3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr_3.size

8

In [14]:
arr_3.shape

(2, 4)

In [15]:
arr_3.ndim

2

In [16]:
list_2 = [[1,2,3,4] , [5,6,7,8,9]]

arr_3 = np.array(list_2)
arr_3

<ipython-input-16-13bf7689b1a6>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr_3 = np.array(list_2)


array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 9])], dtype=object)

In [17]:
list_2 = [[1, 2,3,4] , [5,6,7,8,9]]

arr_3 = np.array(list_2)
arr_3

NameError: name 'NUll' is not defined

In [19]:
list_2 = [[True, None,None,None] , [None,6,7,8]]

arr_3 = np.array(list_2)
arr_3

array([[True, None, None, None],
       [None, 6, 7, 8]], dtype=object)

In [26]:
list_1 = [True , 1 , 2]
list_2 = [2 , 1 , 2]

arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

In [27]:
arr_1

array([1, 1, 2])

In [28]:
arr_2

array([2, 1, 2])

In [29]:
arr_1 + arr_2

array([3, 2, 4])

In [25]:
None + 1

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [30]:
#2 . create an array with arange function

np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.arange(2,8)

array([2, 3, 4, 5, 6, 7])

In [32]:
np.arange(2,8 , -1)

array([], dtype=int64)

In [33]:
np.arange(12,8 , -1)

array([12, 11, 10,  9])

In [34]:
#3. creating an array using linspace

np.linspace(1,10,50)

# - generate 50 values from 1 to 10 where both 1 and 10 are inclusive

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
1.36734694 - 1.18367347

0.18367347

In [36]:
8.89795918 - 8.71428571

0.18367347000000045

In [37]:
#4 . zeros , ones , eye

# zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
arry_lin = np.linspace(1,10,50)

In [44]:
np.zeros_like(arry_lin)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
arr_4 = np.ones((3,4,2,10,10))

In [48]:
arr_4.size

24

In [49]:
arr_4.shape

(3, 4, 2)

In [50]:
arr_4.ndim

3

In [52]:
arr_4

array([[[[[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]]],


        [[[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.]],

         [[1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1., 1., 1.],
          ...,
          [1., 1., 1., ..., 1., 1., 1.],
          [1., 1., 1., ..., 1.

In [54]:
# eye - (indeity array) - n*n

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
# random.rand

In [67]:
np.random.rand(3,1)

array([[0.94290871],
       [0.43380609],
       [0.96729933]])

In [72]:
np.random.randint(1,7 , size = (4,5))

array([[2, 5, 6, 3, 5],
       [1, 6, 3, 4, 4],
       [5, 3, 6, 3, 6],
       [2, 6, 1, 3, 1]])

In [78]:
np.random.randint(1,7)

4

# Reshaping of an array

In [79]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [80]:
a.shape

(6,)

In [81]:
b = a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
6

2-d

1,6
2,3
6,1
3,2

3d-

1,6,1
2,3,1
1,1,6

array([0, 1, 2, 3, 4, 5])

In [83]:
b = a.reshape(2,3,1)

In [86]:
b.ndim

3

In [88]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [89]:
c = np.arange(15).reshape(5,3)

In [90]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [91]:
c.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [95]:
Asian_coutries = np.array(['India' , 'Pakistan' , 'China' , 'japan' , 'bangladesh' , 'sri lanka' , 'nepal' , 'Thailand'])

In [97]:
Asian_coutries.reshape(2,4)

array([['India', 'Pakistan', 'China', 'japan'],
       ['bangladesh', 'sri lanka', 'nepal', 'Thailand']], dtype='<U10')

In [ ]:
int - int 64  and int 32
float - float 64 , float 32
string - u

In [102]:
Asian_coutries = np.array(['India' , 'Pakistan' , 'China' , 'japan' , 'bangladesh' , 'sri lanka' , 'nepal' , 'Thailand'])

In [103]:
Asian_coutries

array(['India', 'Pakistan', 'China', 'japan', 'bangladesh', 'sri lanka',
       'nepal', 'Thailand'], dtype='<U10')

In [104]:
# int - string
# string - int

NameError: name 'string' is not defined

In [105]:
# infer

c = np.arange(100).reshape(2,5,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [108]:
c = np.arange(50).reshape(5,2,-1)

In [109]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [ ]:
# Ravel() fucntion - used ot cinvert ndim to 1 dim

In [113]:
a = Asian_coutries.reshape(2,2,2)

In [114]:
a

array([[['India', 'Pakistan'],
        ['China', 'japan']],

       [['bangladesh', 'sri lanka'],
        ['nepal', 'Thailand']]], dtype='<U10')

In [115]:
a.ravel()

array(['India', 'Pakistan', 'China', 'japan', 'bangladesh', 'sri lanka',
       'nepal', 'Thailand'], dtype='<U10')

In [ ]:
mutable - when assignment is possible

In [117]:
a[1][0]

array(['bangladesh', 'sri lanka'], dtype='<U10')

In [118]:
Asian_coutries

array(['India', 'Pakistan', 'China', 'japan', 'bangladesh', 'sri lanka',
       'nepal', 'Thailand'], dtype='<U10')

In [120]:
Asian_coutries[1] = 'afsaan'

In [123]:
c = Asian_coutries.reshape(2,4)

In [126]:
print(c.ravel())

['India' 'afsaan' 'China' 'japan' 'bangladesh' 'sri lanka' 'nepal'
 'Thailand']


In [127]:
c

array([['India', 'afsaan', 'China', 'japan'],
       ['bangladesh', 'sri lanka', 'nepal', 'Thailand']], dtype='<U10')

In [128]:
a = 'afsaan'

AttributeError: 'str' object has no attribute 'reverse'

In [130]:
# Arithmatic operaton on array elemtwise

In [140]:
a = np.array([10,20,30,40])
b = np.array([5,10,30,45])

In [143]:
a - b

array([0, 0, 0, 0])

In [133]:
a + 5

array([ 5, 10,  0, -5])

In [134]:
a%5

array([0, 0, 0, 0])

In [135]:
a < 5

array([False, False, False, False])

In [ ]:
# matrix multiplication

arr_1 = m * n
arr_2 = n * p

result = m * p

In [144]:
array1 = [[1,2,3] , [4,5,6]]

array2 = [[1,4,7] , [2,5,8] , [3,6,9]]

In [146]:
np.array(array1) * np.array(array2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [148]:
new_array = np.dot(np.array(array1) , np.array(array2))

In [149]:
new_array

array([[ 14,  32,  50],
       [ 32,  77, 122]])

In [150]:
# Unary operations

new_array.sum()

327

In [151]:
new_array.min()

14

In [152]:
new_array.max()

122

In [153]:
# sum of each rows

# 0 - column
# 1- rows

new_array.sum(axis = 0)

array([ 46, 109, 172])

In [154]:
new_array.sum(axis = 1)

array([ 96, 231])

In [155]:
new_array.min(axis = 0)

array([14, 32, 50])

In [156]:
new_array.min(axis = 1)

array([14, 32])